function [SimCfg, GeoCfg, RfCfg, AntCfg, AlgoCfg, OutCfg, CfgDiag] = linkInitConfig(simCfgIn)
%LINKINITCONFIG 系统参数初始化
%
% 功能：
%   初始化链路仿真工程的全部配置参数，包括：
%   1. 仿真场景配置 SimCfg
%   2. 几何与坐标配置 GeoCfg
%   3. 射频链路预算配置 RfCfg
%   4. 天线方向图配置 AntCfg
%   5. 算法配置 AlgoCfg
%   6. 输出配置 OutCfg
%   7. 配置诊断 CfgDiag
%
% 当前版本：
%   - 频率：4.95 GHz
%   - 发射功率：20 dBm
%   - Tx：弹载天线真实 CSV 方向图
%   - Rx：地面四臂螺旋天线真实 CSV 方向图
%
% 说明：
%   当前频率改为 4.95GHz，是为了严格按照老师给的方向图表格频点计算。
%   也就是说：
%   1. 自由空间路径损耗 FSPL 按 4.95GHz 计算；
%   2. 天线方向图也按 4.95GHz 频点读取；
%   3. 不再是“5GHz 链路 + 4.95GHz 方向图近似”。

%% 输入检查
if nargin < 1 || isempty(simCfgIn)
    simCfgIn = struct();
end

%% 工程根目录
thisFile = mfilename('fullpath');
configDir = fileparts(thisFile);
rootDir = fileparts(configDir);

%% ========================================================================
%  1. SimCfg：仿真场景配置
% =========================================================================

SimCfg = struct();

SimCfg.rootDir = rootDir;

SimCfg.scenarioName = getFieldOrDefault( ...
    simCfgIn, ...
    'scenarioName', ...
    'tc06_realistic_local_xyz');

SimCfg.inputMode = getFieldOrDefault( ...
    simCfgIn, ...
    'inputMode', ...
    'synthetic');

SimCfg.useSyntheticTrack = strcmpi(SimCfg.inputMode, 'synthetic');

SimCfg.enablePlot = getFieldOrDefault( ...
    simCfgIn, ...
    'enablePlot', ...
    true);

SimCfg.saveFigure = getFieldOrDefault( ...
    simCfgIn, ...
    'saveFigure', ...
    true);

SimCfg.rngSeed = getFieldOrDefault( ...
    simCfgIn, ...
    'rngSeed', ...
    20260514);

SimCfg.txTrackFile = getFieldOrDefault( ...
    simCfgIn, ...
    'txTrackFile', ...
    fullfile(rootDir, 'input', 'tx_track.csv'));

SimCfg.rxTrackFile = getFieldOrDefault( ...
    simCfgIn, ...
    'rxTrackFile', ...
    fullfile(rootDir, 'input', 'rx_track.csv'));

SimCfg.timeAlignment = getFieldOrDefault( ...
    simCfgIn, ...
    'timeAlignment', ...
    'linear');

SimCfg.enableGpsConvert = getFieldOrDefault( ...
    simCfgIn, ...
    'enableGpsConvert', ...
    false);

SimCfg.enableOmniReference = getFieldOrDefault( ...
    simCfgIn, ...
    'enableOmniReference', ...
    true);

SimCfg.enableEnvelope = getFieldOrDefault( ...
    simCfgIn, ...
    'enableEnvelope', ...
    true);

%% ========================================================================
%  2. GeoCfg：坐标系与姿态配置
% =========================================================================

GeoCfg = struct();

GeoCfg.coordinateMode = getFieldOrDefault( ...
    simCfgIn, ...
    'coordinateMode', ...
    'local_xyz');

% linkCalcGeometrySeries.m 中会用到这个字段
GeoCfg.originDefinition = getFieldOrDefault( ...
    simCfgIn, ...
    'originDefinition', ...
    'Tx/Rx local XYZ coordinate system');

GeoCfg.localFrame = getFieldOrDefault( ...
    simCfgIn, ...
    'localFrame', ...
    'ENU');

GeoCfg.distanceRule = getFieldOrDefault( ...
    simCfgIn, ...
    'distanceRule', ...
    'distance is calculated only from Tx/Rx coordinates');

GeoCfg.xAxis = getFieldOrDefault( ...
    simCfgIn, ...
    'xAxis', ...
    'local forward');

GeoCfg.yAxis = getFieldOrDefault( ...
    simCfgIn, ...
    'yAxis', ...
    'local right');

GeoCfg.zAxis = getFieldOrDefault( ...
    simCfgIn, ...
    'zAxis', ...
    'up');

GeoCfg.rotationOrder = getFieldOrDefault( ...
    simCfgIn, ...
    'rotationOrder', ...
    'Rz(yaw)*Ry(pitch)*Rx(roll)');

GeoCfg.bodyFrame = getFieldOrDefault( ...
    simCfgIn, ...
    'bodyFrame', ...
    'X-forward_Y-right_Z-up');

GeoCfg.body_z_direction = getFieldOrDefault( ...
    simCfgIn, ...
    'body_z_direction', ...
    'up');

GeoCfg.boresightAxis = getFieldOrDefault( ...
    simCfgIn, ...
    'boresightAxis', ...
    'X');

GeoCfg.angleConvention = getFieldOrDefault( ...
    simCfgIn, ...
    'angleConvention', ...
    'AzEl');

GeoCfg.timeAlignment = getFieldOrDefault( ...
    simCfgIn, ...
    'timeAlignment', ...
    SimCfg.timeAlignment);

GeoCfg.rejectDistanceInput = getFieldOrDefault( ...
    simCfgIn, ...
    'rejectDistanceInput', ...
    true);

%% ========================================================================
%  3. RfCfg：射频与链路预算配置
% =========================================================================

RfCfg = struct();

% 发射功率：20 dBm
RfCfg.Pt = getFieldOrDefault( ...
    simCfgIn, ...
    'Pt', ...
    20);

% 接收机灵敏度，后续如果有真实指标再改
RfCfg.Sens = getFieldOrDefault( ...
    simCfgIn, ...
    'Sens', ...
    -90);

% 按老师方向图表格频率计算：4.95 GHz
RfCfg.f = getFieldOrDefault( ...
    simCfgIn, ...
    'f', ...
    4.95e9);

% 光速，单位 m/s
RfCfg.c = getFieldOrDefault( ...
    simCfgIn, ...
    'c', ...
    299792458);

% 其他固定损耗，当前先设为 0 dB
RfCfg.L_other = getFieldOrDefault( ...
    simCfgIn, ...
    'L_other', ...
    0);

% 目标链路余量，当前先设为 3 dB
RfCfg.Margin_target = getFieldOrDefault( ...
    simCfgIn, ...
    'Margin_target', ...
    3);

% GHz 显示用字段
RfCfg.freqGHz = RfCfg.f / 1e9;

%% ========================================================================
%  4. AntCfg：天线方向图配置
% =========================================================================

AntCfg = struct();

AntCfg.tx = struct();
AntCfg.rx = struct();

AntCfg.tx.type = getFieldOrDefault( ...
    simCfgIn, ...
    'txAntennaType', ...
    'pattern');

AntCfg.rx.type = getFieldOrDefault( ...
    simCfgIn, ...
    'rxAntennaType', ...
    'pattern');

AntCfg.tx.omni_gain_dbi = getFieldOrDefault( ...
    simCfgIn, ...
    'txOmniGainDbi', ...
    0);

AntCfg.rx.omni_gain_dbi = getFieldOrDefault( ...
    simCfgIn, ...
    'rxOmniGainDbi', ...
    0);

AntCfg.tx.patternSource = getFieldOrDefault( ...
    simCfgIn, ...
    'txPatternSource', ...
    'csv');

AntCfg.rx.patternSource = getFieldOrDefault( ...
    simCfgIn, ...
    'rxPatternSource', ...
    'csv');

AntCfg.tx.patternFile = getFieldOrDefault( ...
    simCfgIn, ...
    'txPatternFile', ...
    fullfile(rootDir, 'input', 'tx_antenna_pattern.csv'));

AntCfg.rx.patternFile = getFieldOrDefault( ...
    simCfgIn, ...
    'rxPatternFile', ...
    fullfile(rootDir, 'input', 'rx_antenna_pattern.csv'));

AntCfg.interpolation = getFieldOrDefault( ...
    simCfgIn, ...
    'gainInterpolation', ...
    'linear');

AntCfg.outOfBound = getFieldOrDefault( ...
    simCfgIn, ...
    'gainOutOfBound', ...
    -100);

AntCfg.angleInputType = getFieldOrDefault( ...
    simCfgIn, ...
    'angleInputType', ...
    'PhiTheta');

%% Tx 弹载天线角度映射
% 老师说明：
%   phi270 theta90 是头
%   phi90  theta90 是弹尾
%
% 若几何模块中：
%   Az = 0   表示弹头方向
%   Az = 180 表示弹尾方向
%
% 则：
%   Phi = mod(Az + 270, 360)

AntCfg.tx.angleMap = struct();

AntCfg.tx.angleMap.description = ...
    'missile side antenna, phi270 theta90=head, phi90 theta90=tail';

AntCfg.tx.angleMap.phiOffsetDeg = getNestedFieldOrDefault( ...
    simCfgIn, ...
    {'txAngleMap', 'phiOffsetDeg'}, ...
    270);

% Tx 方向图第二角度范围是 0~180。
% theta=0 是天顶，theta=90 是水平头/尾方向。
% 所以：
%   Theta = 90 - El
AntCfg.tx.angleMap.thetaMode = getNestedFieldOrDefault( ...
    simCfgIn, ...
    {'txAngleMap', 'thetaMode'}, ...
    'zenith0_horizon90');

AntCfg.tx.angleMap.phiWrap = true;

%% Rx 地面天线角度映射
AntCfg.rx.angleMap = struct();

AntCfg.rx.angleMap.description = ...
    'ground quadrifilar helix antenna, upward hemisphere coverage';

AntCfg.rx.angleMap.phiOffsetDeg = getNestedFieldOrDefault( ...
    simCfgIn, ...
    {'rxAngleMap', 'phiOffsetDeg'}, ...
    0);

% Rx 方向图第二角度范围是 -90~90。
% 它本身就是仰角 El，所以不做 90-El。
AntCfg.rx.angleMap.thetaMode = getNestedFieldOrDefault( ...
    simCfgIn, ...
    {'rxAngleMap', 'thetaMode'}, ...
    'identity');

AntCfg.rx.angleMap.phiWrap = true;

AntCfg.tx.polarization = getFieldOrDefault( ...
    simCfgIn, ...
    'txPolarization', ...
    'unknown');

AntCfg.rx.polarization = getFieldOrDefault( ...
    simCfgIn, ...
    'rxPolarization', ...
    'LHCP');

%% ========================================================================
%  5. AlgoCfg：算法配置
% =========================================================================

AlgoCfg = struct();

AlgoCfg.enableOmniReference = getFieldOrDefault( ...
    simCfgIn, ...
    'enableOmniReference', ...
    SimCfg.enableOmniReference);

AlgoCfg.enableEnvelope = getFieldOrDefault( ...
    simCfgIn, ...
    'enableEnvelope', ...
    SimCfg.enableEnvelope);

AlgoCfg.azBinDeg = getFieldOrDefault( ...
    simCfgIn, ...
    'azBinDeg', ...
    5);

AlgoCfg.elBinDeg = getFieldOrDefault( ...
    simCfgIn, ...
    'elBinDeg', ...
    5);

AlgoCfg.keepDebugFields = getFieldOrDefault( ...
    simCfgIn, ...
    'keepDebugFields', ...
    true);

AlgoCfg.savePatternQueryAngles = getFieldOrDefault( ...
    simCfgIn, ...
    'savePatternQueryAngles', ...
    true);

%% ========================================================================
%  6. OutCfg：输出配置
% =========================================================================

OutCfg = struct();

OutCfg.outputDir = getFieldOrDefault( ...
    simCfgIn, ...
    'outputDir', ...
    fullfile(rootDir, 'output'));

OutCfg.figureDir = getFieldOrDefault( ...
    simCfgIn, ...
    'figureDir', ...
    fullfile(OutCfg.outputDir, 'figures'));

OutCfg.outputCsv = getFieldOrDefault( ...
    simCfgIn, ...
    'outputCsv', ...
    fullfile(OutCfg.outputDir, 'link_result.csv'));

OutCfg.outputMat = getFieldOrDefault( ...
    simCfgIn, ...
    'outputMat', ...
    fullfile(OutCfg.outputDir, 'link_result.mat'));

OutCfg.reportFile = getFieldOrDefault( ...
    simCfgIn, ...
    'reportFile', ...
    fullfile(OutCfg.outputDir, 'link_report.txt'));

OutCfg.figureFormat = getFieldOrDefault( ...
    simCfgIn, ...
    'figureFormat', ...
    'png');

OutCfg.enablePlot = SimCfg.enablePlot;
OutCfg.saveFigure = SimCfg.saveFigure;

if ~exist(OutCfg.outputDir, 'dir')
    mkdir(OutCfg.outputDir);
end

if ~exist(OutCfg.figureDir, 'dir')
    mkdir(OutCfg.figureDir);
end

%% ========================================================================
%  7. CfgDiag：配置诊断
% =========================================================================

CfgDiag = struct();

CfgDiag.message = ...
    '配置初始化完成。当前模式：4.95GHz、Pt=20dBm、Tx/Rx均使用真实CSV方向图。';

CfgDiag.rootDir = rootDir;
CfgDiag.scenarioName = SimCfg.scenarioName;
CfgDiag.inputMode = SimCfg.inputMode;

CfgDiag.coordinateRule = ...
    '输入只能是 Tx/Rx 坐标，距离 d 只能由坐标计算。';

CfgDiag.angleRule = ...
    '几何模块输出 Az/El，天线模块映射到老师方向图 Phi/Theta。';

CfgDiag.rfSummary = sprintf( ...
    'Pt=%.2f dBm, Sens=%.2f dBm, f=%.3f GHz, L_other=%.2f dB, Margin_target=%.2f dB', ...
    RfCfg.Pt, ...
    RfCfg.Sens, ...
    RfCfg.freqGHz, ...
    RfCfg.L_other, ...
    RfCfg.Margin_target);

CfgDiag.txPatternFile = AntCfg.tx.patternFile;
CfgDiag.rxPatternFile = AntCfg.rx.patternFile;

CfgDiag.txPatternFileExist = exist(AntCfg.tx.patternFile, 'file') == 2;
CfgDiag.rxPatternFileExist = exist(AntCfg.rx.patternFile, 'file') == 2;

CfgDiag.txTrackFileExist = exist(SimCfg.txTrackFile, 'file') == 2;
CfgDiag.rxTrackFileExist = exist(SimCfg.rxTrackFile, 'file') == 2;

CfgDiag.warnings = {};

if strcmpi(AntCfg.tx.type, 'pattern') && ~CfgDiag.txPatternFileExist
    CfgDiag.warnings{end+1} = ['Tx方向图文件不存在: ', AntCfg.tx.patternFile];
end

if strcmpi(AntCfg.rx.type, 'pattern') && ~CfgDiag.rxPatternFileExist
    CfgDiag.warnings{end+1} = ['Rx方向图文件不存在: ', AntCfg.rx.patternFile];
end

if strcmpi(SimCfg.inputMode, 'csv')
    if ~CfgDiag.txTrackFileExist
        CfgDiag.warnings{end+1} = ['Tx轨迹文件不存在: ', SimCfg.txTrackFile];
    end

    if ~CfgDiag.rxTrackFileExist
        CfgDiag.warnings{end+1} = ['Rx轨迹文件不存在: ', SimCfg.rxTrackFile];
    end
end

rng(SimCfg.rngSeed);

%% 控制台提示
fprintf('\n========== linkInitConfig ==========\n');
fprintf('工程目录: %s\n', rootDir);
fprintf('场景名称: %s\n', SimCfg.scenarioName);
fprintf('输入模式: %s\n', SimCfg.inputMode);
fprintf('频率: %.3f GHz\n', RfCfg.freqGHz);
fprintf('发射功率: %.2f dBm\n', RfCfg.Pt);
fprintf('接收灵敏度: %.2f dBm\n', RfCfg.Sens);
fprintf('其他损耗: %.2f dB\n', RfCfg.L_other);
fprintf('目标链路余量: %.2f dB\n', RfCfg.Margin_target);
fprintf('Tx天线类型: %s\n', AntCfg.tx.type);
fprintf('Rx天线类型: %s\n', AntCfg.rx.type);
fprintf('Tx方向图文件: %s\n', AntCfg.tx.patternFile);
fprintf('Rx方向图文件: %s\n', AntCfg.rx.patternFile);
fprintf('GeoCfg.originDefinition: %s\n', GeoCfg.originDefinition);
fprintf('Tx thetaMode: %s\n', AntCfg.tx.angleMap.thetaMode);
fprintf('Rx thetaMode: %s\n', AntCfg.rx.angleMap.thetaMode);

if ~isempty(CfgDiag.warnings)
    fprintf('\n配置警告:\n');
    for i = 1:numel(CfgDiag.warnings)
        fprintf('  [%d] %s\n', i, CfgDiag.warnings{i});
    end
end

fprintf('====================================\n\n');

end

%% ========================================================================
%  辅助函数 1：读取一级字段
% =========================================================================

function val = getFieldOrDefault(s, name, defaultVal)
if isstruct(s) && isfield(s, name) && ~isempty(s.(name))
    val = s.(name);
else
    val = defaultVal;
end
end

%% ========================================================================
%  辅助函数 2：读取嵌套字段
% =========================================================================

function val = getNestedFieldOrDefault(s, fieldPath, defaultVal)

val = defaultVal;

if ~isstruct(s)
    return;
end

tmp = s;

for i = 1:numel(fieldPath)
    name = fieldPath{i};

    if isstruct(tmp) && isfield(tmp, name) && ~isempty(tmp.(name))
        tmp = tmp.(name);
    else
        return;
    end
end

val = tmp;

end